### ISSUE TITLE
--installmods fails due to incorrectly named download file from redirect

### ISSUE THREAD

**Issue by mahmed2000** [0neGal/viper-sh#1]
The thunderstore api forces a redirect which makes wget not follow redirect Content-Type headers and saves the file as index.html and not as the proper zip file. Fixed by adding --trust-server-names flag on line 226:

`wget "$MOD" > /dev/null && {`
to
`wget --trust-server-names "$MOD" > /dev/null && {`

**Comment by 0neGal** [comment]
This should now be fixed with [`00e77e1`](https://github.com/0neGal/viper-sh/commit/00e77e12fe4607f51bda536e18ee808907ae4213). This likely happened because my system symlinks `/usr/bin/aria2c` to `/usr/bin/wget`, so I may have accidentally run this with aria2c without realizing it. I can't say for sure considering it's been a bit since I wrote the code.

It's also possible Thunderstore added this after the fact, I wouldn't know.
